name    'mtomic/awscli'
version '0.1.0'
source 'https://github.com/mtomic/mtomic-puppet-awscli'
author 'Marko Tomic'
license 'Apache License, Version 2.0'
summary 'Install awscli'
description 'Install awscli'
project_page 'https://github.com/mtomic/mtomic-puppet-awscli'
